### ISSUE TITLE
MessageServiceFramework的pfx无法导入

### ISSUE THREAD

**Issue by eaglebetter** [znlgis/PDF.NET-SOD#2]
PDF.NET.MSF.2017.pfx或PdfNetMsfKey.pfx输入SlnKey.txt中的密码都不正确。

**Comment by znlgis** [comment]
PDF.NET.MSF.2017:2017.3.5.19.38
PDF.NET.EF.2017:2017.3.5.19.41
冒号后面的才是密码，隐藏的有点深
